### ISSUE TITLE
calendarPlot() palette question

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#148]
More of a question than an issue,  I seem to be having trouble utilizing the "palette" feature of the calendarPlot() function. I've tried a couple of different options and each time I get the same plot with the same colors automatically generated.   

Would it be possible to get some guidance on accessing/using this feature? Additionally, would it be possible to be able to access and apply the same color palette used in the AirSensor DataViewer through the AirSensor package to plots in RStudio?  (e.g., for the calendarPlot() or maps)

thanks in advance!

______________________________

library(AirSensor)
library(stringr)
library(rlang)
 library(RColorBrewer)

setArchiveBaseUrl("http://smoke.mazamascience.com/data/PurpleAir")

pas <- pas_load(archival = TRUE)
pat <- pat_load("SCUV_01", startdate = "2018-01-01", enddate = "2019-01-01")

pat_calendarPlot(pat)
pat_calendarPlot(pat, palette = c("red", "orange", "yellow", "green"))
pat_calendarPlot(pat, palette = "YlGnBu")

**Comment by jonathancallahan** [comment]
The calendarPlot functionality is being moved to the **AirMonitorPlots** package. That package hosts a variety of plotting functions that operate on **AirSensor** `airsensor` objects and the functionally equivalent **PWFSLSmoke** `ws_monitor` objects.

A future release of the **AirSensor** package may include a `pat_calendarPlot()` function that wraps the function in the **AirMonitorPlots** package.e
