### ISSUE TITLE
t test error with pat_createAirSensor()

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#157]
I keep encountering the same error using the function pat_createAirSensor():

_Error in t.test.default(x, y, paired = FALSE) : data are essentially constant_ 

The strange thing is I encounter this error even when I specify that I would only like to use one channel and/or the qc_algorithm hourly_AB_00 - both cases where I believe the t test should not be applied. Additionally, a quick check of the data from channels a and b reveals that there are no major issues with missing or out of spec data and the two channels seem to agree with one another.  Should I be utilizing the function differently? (example code below)
______________

library(AirSensor)

setArchiveBaseUrl("http://smoke.mazamascience.com/data/PurpleAir")

pas <- pas_load(archival = TRUE)

tempdata <- pat_load("SCIV_03", startdate = "2018-01-01", enddate = "2019-09-01")
sensorData <- pat_createAirSensor(tempdata, period = "1 hour", parameter = "pm25", channel = "ab", qc_algorithm = "hourly_AB_01", min_count = 20)
plot(tempdata$data$datetime, tempdata$data$pm25_A, ylim = c(0,100))
points(tempdata$data$datetime, tempdata$data$pm25_B, col = "red")

tempdata <- pat_load("SCIV_06", startdate = "2018-01-01", enddate = "2019-09-01")
sensorData <- pat_createAirSensor(tempdata, period = "1 hour", parameter = "pm25", channel = "ab", qc_algorithm = "hourly_AB_01", min_count = 20)
plot(tempdata$data$datetime, tempdata$data$pm25_A, ylim = c(0,100))
points(tempdata$data$datetime, tempdata$data$pm25_B, col = "red")

sensorData <- pat_createAirSensor(tempdata, period = "1 hour", parameter = "pm25", channel = "ab", qc_algorithm = "hourly_AB_00", min_count = 20)

sensorData <- pat_createAirSensor(tempdata, period = "1 hour", parameter = "pm25", channel = "a", qc_algorithm = "hourly_AB_00", min_count = 20)

sensorData <- pat_createAirSensor(tempdata, period = "1 hour", parameter = "pm25", channel = "b", qc_algorithm = "hourly_AB_00", min_count = 20)

**Comment by jonathancallahan** [comment]
Fixed in AirSensor version 0.5.5.
