### ISSUE TITLE
issue with MazamaCoreUtils/pat_load

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#161]
I am getting the following error with pat_load(). I have confirmed for this sensor, for this time frame that there is data in the archive.  

Error in pat_load("SCAP_50", startdate = 20180101, enddate = 20180110) : 
  Error in MazamaCoreUtils::parseDatetime(datestamp, timezone = timezone) : 
  No datetimes could be parsed.

______________________________________________________

Code:

library(AirSensor)
setArchiveBaseUrl("http://smoke.mazamascience.com/data/PurpleAir")
pas <- pas_load(archival = TRUE)
tempdata <- pat_load("SCAP_50", startdate = 20180101, enddate = 20180201)

**Comment by jonathancallahan** [comment]
Resolved in version 0.5.6.
