### ISSUE TITLE
check on local time in all SoH_ functions

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirSensor#165]
All of the state-of-health functions should:

* trim any incoming time series to local time day boundaries
* calculate daily metrics based on local time

**Comment by kayleighwilson** [comment]
This is currently in an odd state. Both `SoH_dailyPCTValid` and `SoH_dailyPCTReporting` call `pat_aggregateOutlierCounts` for the time period of "1 day" which appears to be doing strange magic with the timezones.

**Comment by kayleighwilson** [comment]
Update: I reduced the aggregation period in `pat_aggregateOutlierCounts` to 1 hour and used dplyr tools to do additional aggregation to avoid timezone issues. There still might be a better way to work out the problem but for now, this is the functioning work around
