### ISSUE TITLE
Review the QC algorithm

### ISSUE THREAD

**Issue by hansmrtn** [MazamaScience/AirSensor#171]
As seen [here](http://tools.mazamascience.com/airsensor-test/app/?_values_&lookback_select=%223%22&nav=%22explore%22&date_select=%222019-10-27%22&pas_select=%22SCBB_02%22&tab=%22comp%22), a lot of data is removed. The error looks to be wildfire smoke, but the outlier filter currently removes the data.

**Comment by jonathancallahan** [comment]
This probably doesn't have anything to do with outlier filtering but rather with the QC algorithm. The same problem occurred in downtown LA on July 4/5. The algorithm defined in `PurpleAirQC_hourly_AB_01()` is too stringent and tosses out data where the A and B channel differ by a lot . But these differences happen precisely when there are big smoke events. 

We need to come up with a `PurpleAirQC_hourl_AB_02()` that is more tolerant of A/B channel differences when smoke levels are high.
