### ISSUE TITLE
timezone bug in pat_filterDate()

### ISSUE THREAD

**Issue by kayleighwilson** [MazamaScience/AirSensor#186]
The default timezone in `pat_filterDate` is "America/Los_Angeles" which creates a problem if a timezone is not specified when calling the function. Here is a case that demonstrates the problem: 

```
library(MazamaCoreUtils)
setArchiveBaseUrl("http://smoke.mazamascience.com/data/PurpleAir")
pas <- pas_load(archival = TRUE)
pat <- pat_createNew(pas,"GRIZZLY WAY", startdate = 20191015, enddate = 20191118, 
baseURL = "https://api.thingspeak.com/channels/")
start <- MazamaCoreUtils::parseDatetime(datetime = 20191101, 
timezone = small_pat$meta$timezone)
end <- MazamaCoreUtils::parseDatetime(datetime = 20191102, 
timezone = small_pat$meta$timezone)
a <- pat_filterDate(grizzly_pat, startdate = start, enddate = end)
b <- pat_filterDate(grizzly_pat, startdate = start, enddate = end, 
timezone = grizzly_pat$meta$timezone)
range(a$data$datetime)
range(b$data$datetime)
``` 
This example creates two test variables using `pat_filterDate`. The range of `b` is correct because the station's local timezone ("America/Denver") was provided, but the range of `a` is offset by an entire day when no timezone was provided and the default (America/Los_Angeles) is used, rather than just being offset by an additional hour. The underlying problem most likely resides in `MazamaCoreUtils::dateRange'.

**Comment by jonathancallahan** [comment]
resolved in AirSensor 0.5.14
