### ISSUE TITLE
pas_upgrade() function

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirSensor#203]
The version 0.5 database for SCAQMD is available at:

http://smoke.mazamascience.com/data/PurpleAir/pas/

In anticipation of the need to recreate this database at a new "v1" location, we will need to read in data created with the 0.5 R scripts and convert it to what will eventually be released as the 1.0 version.

This function should have the following, simple structure:

```
pas_upgrade <- function(
  pas = NULL
) {
  # ----- test incoming pas for validity
  # ----- add new columns based on old pas
  # ----- remove unneeded columns from old pas
  # ----- return
}
```

This function could then be used in a script that runs on the data archive host:

1. create a vector of absolute paths for the old pas objects
2. ingest the pas objects
3. feed them to pas_upgrade()
4. save them to the new "v1" location

**Comment by hansmrtn** [comment]
Include: Create an example script that finds files and upgrades in one directory and writes them to a new directory.
