### ISSUE TITLE
pat_dygraph() should support pressure

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirSensor#218]
The new `pat_createNew()` function creates `pat` objects with a `pressure` column. The `pat_dygraph()` function should support the display of this parameter.

**NOTE:**

We won't include `pressure` in `pat_multiplot()` defaults because there is no evidence that it affects PM measurements whereas both `temperature` and `humidity` do.

**Comment by hansmrtn** [comment]
What is the unit of the pressure data?
