### ISSUE TITLE
Issue with pat_externalFit()

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#242]
Here is more information on the issue mentioned during today's meeting. 

issue: pat_externalFit does not seem to be applying the correct qc algorithm when that argument is included (in the example below it seems to default to algorithm 01, even though algorithm 01 fails with this dataset while 00 and 02 do seem to work)

example code: 

library(AirSensor)
setArchiveBaseUrl("http://data.mazamascience.com/PurpleAir/v1/")
pas <- pas_load()

id <- pas_getDeviceDeploymentIDs(pas, "SCAP_50")
pat <- pat_load(id = id, pas = pas, label = "SCAP_50", startdate = 20200701, enddate = 20200715, timezone = "America/Los_Angeles")
pat_multiPlot(pat)
pat_externalFit(pat) # fails here
pat_externalFit(pat, qc_algorithm = "hourly_AB_00") # fails here
pat_externalFit(pat, qc_algorithm = "hourly_AB_02") # fails here

sensor <- pat_createAirSensor(pat = pat, FUN = PurpleAirQC_hourly_AB_00) # does not fail here
sensor <- pat_createAirSensor(pat = pat, FUN = PurpleAirQC_hourly_AB_01) # fails here
sensor <- pat_createAirSensor(pat = pat, FUN = PurpleAirQC_hourly_AB_02) # does not fail here

**Comment by jonathancallahan** [comment]
The places where this fails generates warnings like the following:

```
Warning messages:
1: In tstat + c(-cint, cint) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

This is already identified in https://github.com/MazamaScience/AirSensor/issues/237

Fixing that issue will hopefully fix this one.
