### ISSUE TITLE
possible issue with pat_load()

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#243]
Brandon and I are occasionally seeing the following error when using pat_load() - I'm not sure it's an actual "issue", but it would be great if you could provide some insight into why it's happening. This was observed using ver 0.9.9 of the package, but I re-ran the code today (with the updates to the archive) and it still seems to be occurring. Thanks in advance!

Error Message: 

Error in metaList[[length(metaList)]] :
  attempt to select less than one element in integerOneIndex

Example Code:  (seeing errors for "SCSB_02" (i = 1) and "SCSB_09" (i = 5), among others in this list. However, pat_createNew seems to work for both of these sensors.

library(AirSensor); library(stringr)
setArchiveBaseUrl("http://data.mazamascience.com/PurpleAir/v1/")

pas1 <- pas_load(datestamp = "20191001", archival = TRUE)
pas2 <-pas_load(archival = TRUE)
pas_all1 <-  pas_filter(pas = pas1, stringr::str_detect(label, "^[Ss][Cc][Ss][Bb]_"));
pas_all2 <-  pas_filter(pas = pas2, stringr::str_detect(label, "^[Ss][Cc][Ss][Bb]_"));
pas_all <- rbind(pas_all1, pas_all2)
pas_all <- distinct(pas_all, label, .keep_all = TRUE)

sens <- pas_all$label; sens_a <- sens[which(str_detect(sens, " B") == FALSE)]

i = 1; label <- sens_a[i]; pat <- NULL; id <- pas_getDeviceDeploymentIDs(pas_all, label)
pat <- pat_load(id = id, pas = pas_all, label = label, startdate = 20171001, enddate = 20200801, timezone = "America/Los_Angeles")
i = 2; label <- sens_a[i]; pat <- NULL; id <- pas_getDeviceDeploymentIDs(pas_all, label)
pat <- pat_load(id = id, pas = pas_all, label = label, startdate = 20171001, enddate = 20200801, timezone = "America/Los_Angeles")
i = 5; label <- sens_a[i]; pat <- NULL; id <- pas_getDeviceDeploymentIDs(pas_all, label)
pat <- pat_load(id = id, pas = pas_all, label = label, startdate = 20171001, enddate = 20200801, timezone = "America/Los_Angeles")

i = 1; label <- sens_a[i]; pat <- NULL; id <- pas_getDeviceDeploymentIDs(pas_all, label)
pat <- pat_createNew(id = id, pas = pas_all, label = label, startdate = 20171001, enddate = 20200801, timezone = "America/Los_Angeles")
i = 5; label <- sens_a[i]; pat <- NULL; id <- pas_getDeviceDeploymentIDs(pas_all, label)
pat <- pat_createNew(id = id, pas = pas_all, label = label, startdate = 20171001, enddate = 20200801, timezone = "America/Los_Angeles")

**Comment by jonathancallahan** [comment]
In the very first case, the label is `SCSB_02` and the deviceDeploymentID is `4ef4e0901c61b1c3_1860`. No 'pat' object with this deviceDeploymentID was generated when I recently rebuilt the archives. This is probably because I didn't go back and load the older 'pas' object from 20191001.

Indeed, `SCSB_02` is not found in `pas2`. So, in order to generate the missing archival data, I need to create a another script to create monthly 'pat' objects that starts with `pas1`, finds those deviceDeploymentIDs that haven't been created and generates them.
