### ISSUE TITLE
Historical Data Page - Compare Tab (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensor#250]
Historical Data Page - Compare Tab

1. Leaflet map
    - [x] Monitoring station flag should be labeled by monitoring station name
2. Sensor/Monitor comparison plot 
    - [x] Change title to be simpler: i.e. Sensor / Regulatory monitor comparison – PurpleAir [NAME] is x.x km from monitoring site: [Station Name]
    - [x] Add light gray dots to the legend
3. Scatter plot
    - [x] Needs title
    - [x] Need concentration labels 
    - [x] Label monitoring site by name
    - [x] Slope/intercept/R2 sometimes not displayed depending on slope of plot

**Comment by jonathancallahan** [comment]
1. Monitoring station name and sensor label are already available when clicked. I have added an issue to AirSensorDataViewer to enable them for "onHover" events.
