### ISSUE TITLE
Historical Data Page - Raw Data Tab (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensor#251]
Historical Data Page - Raw Data Tab

- [ ]  Improve Aesthetics of the plots --- similar to Latest Data look / feel --- 
- [ ] Plots do not need to be interactive, just improved aesthetically 
- [ ] X-axis labels should be date

**Comment by jonathancallahan** [comment]
This issue needs more specific suggestions to be actionable.
