### ISSUE TITLE
pas_load retrieves pas with different number of variables prior to Sept 2020

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensor#255]
pas loaded prior to Sept. 2020 retrieve data object with 45 variables with extra variable being the $Voc column. After Sept. 2020, pas data objects retrieve data object with 44 variables. 

# Example Code
pas <- pas_load("20190406", archival = TRUE)       # not loading
pas1 <- pas_load("20190611", archival = TRUE)     # not loading
pas2 <- pas_load("20190805", archival = TRUE) 
pas3 <- pas_load("20191005", archival = TRUE)
pas4 <- pas_load("20191205", archival = TRUE)
pas5 <- pas_load("20200105", archival = TRUE)
pas6 <- pas_load("20200305", archival = TRUE)
pas7 <- pas_load("20200505", archival = TRUE)
pas8 <- pas_load("20200705", archival = TRUE)
pas9 <- pas_load("20200905", archival = TRUE)
pas10 <- pas_load("20200910", archival = TRUE) # PAS changes to 44 variables on load
pas11 <- pas_load("20201207", archival = TRUE)

# Work around to join pas with different # of variables
pas_join1 <- rbind(pas2,pas3,pas4,pas5,pas6,pas7,pas8,pas9)
pas_join1$Voc <- NULL
pas_join2 <- rbind(pas_join1,pas10,pas11)

**Comment by jonathancallahan** [comment]
Dealt with the extra "Voc" variable in some early 'pas' objects by simply removing it during the load process. This fix is in **AirSensor** 1.0.7. 

The missing 'pas' objects are being promoted to their own new issue.
