### ISSUE TITLE
revisions to SOH metric descriptions 

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensor#256]
A while ago we discussed making revisions to some of the documentation text for the SOH metrics for clarity, I have made a few suggestions that have been reviewed by the team here and copied them below, please let me know if there are any questions. 

**Percent Valid:** The number of valid (i.e., not NA or out-of-spec) sensor measurements are summed over the course of a calendar day, then divided by the total number of measurements the sensor actually recorded during that day (including NA and out-of-spec values) to return a percentage of the total recorded measurements that are considered plausible. This metric utilizes the same bounds as the ‘pat_qc’ function to identify out-of-spec values. 

**Percent DC**: This function calculates the daily percentage of DC signal recorded by the pm25_A, pm25_B, humidity, and temperature channels. The data are flagged as DC signal when the standard deviation of an hour of data from each channel equals zero. The number of hours with a DC signal are summed over the day and a daily DC percentage for each channel is returned. This metric allows users to identify “sticky values”, or instances of a sensor continuously logging the same value. A high percent DC value indicates the likely occurrence of a “sticky value”, and a zero or low percent DC indicates that the sensor is recording dynamic data. 

**AB t-test**: This function calculates a t-test between the pm25_A, pm25_B. A t-statistic and a p-value will be returned for each day. All returned values are expected to hover near 0 for a properly functioning sensor. The t-statistic and p-value serve to test whether or not the pm25_A and pm25_B data are significantly different based on a student’s t-test. 

An additional suggestion from our team is to consider whether "Other Fit" should be "Met Fit" (given that it involves the temperature and humidity parameters), although this change will be left to your discretion.

**Comment by jonathancallahan** [comment]
All changes were made in **AirSensor** 1.0.7.
