### ISSUE TITLE
404 Error when creating PAT

### ISSUE THREAD

**Issue by masterminnich** [MazamaScience/AirSensor#258]
Hello,

I am completely new to the AirSensor package, so perhaps I am doing something incorrectly. I was trying to follow along with the "Australia on Fire" article and found that I was unable to create any PATs. I'm running the latest build (1.0.7).

```
pas <- pas_createNew(countryCodes = "AU")

pas1 <- filter(pas, label == "Yarragon")

pat <- pat_createNew(
  label = "Yarragon", 
  pas = pas1, 
  startdate = 20210101, 
  enddate = 20210131
)
```

This is the error message I get:
```
WARN [2021-02-10 10:22:38] Channel B: Channel B web service error 404 from:
  https://api.thingspeak.com/channels//feeds.csv?api_key=&start=2020-12-31T13:00:00&end=2021-01-07T13:00:00

Nothing matches the given URI
Channel B web service error 404 from:
  https://api.thingspeak.com/channels//feeds.csv?api_key=&start=2020-12-31T13:00:00&end=2021-01-07T13:00:00
```

Thank you for any help.

**Comment by jonathancallahan** [comment]
If you `View(pas)` you will see that there are two entries for Yarragon: "Yarragon" and "Yarragon B" -- one for each detecter in the PurpleAir sensor.

Both of these detectors are needed to create a 'pat' object and your filtering created a 'pas' object where only the first is present.

Instead you should create the 'pat' object without filtering first:

```
pat <- pat_createNew(
  label = "Yarragon", 
  pas = pas,                # <= Just pass in the original 'pas'
  startdate = 20210101, 
  enddate = 20210131
)
```

If `pas = pas` looks odd to you, just remember that arguments to R functions are just a list of key = value pairs and the ability of leaving off the quotes around the key is just syntactic sugar. The above function call is identical to:

```
pat <- pat_createNew(
  "label" = "Yarragon", 
  "pas" = pas,                # <= Just pass in the original 'pas'
  "startdate" = 20210101, 
  "enddate" = 20210131
)
```
