### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by pratyushagrawal** [MazamaScience/AirSensor#269]
`install.packages("remotes")
remotes::install_github("MazamaScience/AirSensorDataViewer")

AirSensorDataViewer::run_app()`

Using this code I tried running the app, But it shows an error like this-

**[Error in loadNamespace(name) : 
  there is no package called ‘AirSensorDataViewer’]**

**Comment by jonathancallahan** [comment]
This software was custom built for a client and is not expected to be run by end users.

The software is offered as example code only for those curious about Shiny apps.
