### ISSUE TITLE
AirSensor installation error - Linux

### ISSUE THREAD

**Issue by praful-dodda** [MazamaScience/AirSensor#273]
### I created a new-conda environment only to install AirSensor. It's not working. I'm getting the following
Using PKG_LIBS=-ljq
--------------------------- [ANTICONF] --------------------------------
Configuration failed because libjq was not found. Try installing:
 * deb: libjq-dev (Debian, Ubuntu).
 * rpm: jq-devel (Fedora, EPEL)
 * csw: libjq_dev (Solaris)
 * brew: jq (OSX)
If  is already installed set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: jq.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘jqr’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/jqr’
* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
** using staged installation
configure: R_HOME: /nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R
configure: CC: /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cc
configure: CXX: /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-c++
configure: CFLAGS: -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include
configure: CPPFLAGS: -I/nas/longleaf/home/praful/AQM/WRF/Build_WRF/LIBRARIES/grib2/include
configure: CXXFLAGS: -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include
configure: LDFLAGS: -L/nas/longleaf/home/praful/AQM/WRF/Build_WRF/LIBRARIES/grib2/lib
configure: LDFLAGS: -L/nas/longleaf/home/praful/AQM/WRF/Build_WRF/LIBRARIES/grib2/lib
configure: CXX11 is: x86_64-conda_cos6-linux-gnu-c++, CXX11STD is: -std=gnu++11
configure: CXX is: x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
configure: C++11 support available
configure: rgdal: 1.5-28
checking for /usr/bin/svnversion... yes
configure: svn revision: 1158
checking for gdal-config... /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.1.1
checking GDAL version >= 1.11.4... yes
checking GDAL version <= 2.5 or >= 3.0... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/nas/longleaf/home/praful/anaconda3/envs/r_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /nas/longleaf/home/praful/anaconda3/envs/r_env/lib/./libsqlite3.so.0: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
/nas/longleaf/home/praful/anaconda3/envs/r_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /nas/longleaf/home/praful/anaconda3/envs/r_env/lib/libsqlite3.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/rgdal’
* restoring previous ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/rgdal’
ERROR: failed to lock directory ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library’ for modifying
Try removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/00LOCK-tibble’
ERROR: failed to lock directory ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library’ for modifying
Try removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/00LOCK-cli’
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cc
configure: CXX: /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-c++
checking for gdal-config... /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.1.1
checking GDAL version >= 2.0.1... yes
checking for gcc... /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /nas/longleaf/home/praful/anaconda3/envs/r_env/bin/x86_64-conda_cos6-linux-gnu-cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/nas/longleaf/home/praful/anaconda3/envs/r_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /nas/longleaf/home/praful/anaconda3/envs/r_env/lib/./libsqlite3.so.0: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
/nas/longleaf/home/praful/anaconda3/envs/r_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /nas/longleaf/home/praful/anaconda3/envs/r_env/lib/libsqlite3.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘terra’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/terra’
* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.7-2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... yes
checking udunits2.h presence... yes
checking for udunits2.h... yes
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpuF5tjl/R.INSTALL1c491e20bfd3/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/units’
* installing *source* package ‘protolite’ ...
** package ‘protolite’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lprotobuf -lpthread  
<stdin>:1:10: fatal error: google/protobuf/message.h: No such file or directory
compilation terminated.
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because protobuf was not found. Try installing:
 * deb: libprotobuf-dev (Debian, Ubuntu, etc)
 * rpm: protobuf-devel (Fedora, EPEL)
 * csw: protobuf_dev (Solaris)
 * brew: protobuf (OSX)
If protobuf is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a protobuf.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘protolite’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/protolite’
* installing *source* package ‘openair’ ...
** package ‘openair’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/include" -DNDEBUG  -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -I/nas/longleaf/home/praful/anaconda3/envs/r_env/include -Wl,-rpath-link,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/nas/longleaf/home/praful/anaconda3/envs/r_env=/usr/local/src/conda-prefix  -c cluster.cpp -o cluster.o
x86_64-conda_cos6-linux-gnu-cc -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/include" -DNDEBUG  -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -I/nas/longleaf/home/praful/anaconda3/envs/r_env/include -Wl,-rpath-link,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib  -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/nas/longleaf/home/praful/anaconda3/envs/r_env=/usr/local/src/conda-prefix  -c init.c -o init.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/include" -DNDEBUG  -I"/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -I/nas/longleaf/home/praful/anaconda3/envs/r_env/include -Wl,-rpath-link,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /nas/longleaf/home/praful/anaconda3/envs/r_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/nas/longleaf/home/praful/anaconda3/envs/r_env=/usr/local/src/conda-prefix  -c rolling.cpp -o rolling.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib -Wl,-rpath-link,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib -L/nas/longleaf/home/praful/anaconda3/envs/r_env/lib -Wl,-rpath-link,/nas/longleaf/home/praful/anaconda3/envs/r_env/lib -o openair.so cluster.o init.o rolling.o -llapack -lblas -lgfortran -lm -lgomp -lquadmath -lpthread -L/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/lib -lR
/nas/longleaf/home/praful/anaconda3/envs/r_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgomp
collect2: error: ld returned 1 exit status
make: *** [/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/share/make/shlib.mk:6: openair.so] Error 1
ERROR: compilation failed for package ‘openair’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/openair’
* restoring previous ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/openair’
ERROR: dependency ‘terra’ is not available for package ‘raster’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/raster’
ERROR: dependencies ‘protolite’, ‘jqr’ are not available for package ‘geojson’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/geojson’
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/sf’
* installing *source* package ‘sessioninfo’ ...
** package ‘sessioninfo’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘cli’ 3.0.1 is being loaded, but >= 3.1.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘sessioninfo’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/sessioninfo’
* restoring previous ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/sessioninfo’
ERROR: dependencies ‘sf’, ‘geojson’, ‘jqr’ are not available for package ‘geojsonio’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/geojsonio’
ERROR: dependencies ‘geojsonio’, ‘sf’ are not available for package ‘rmapshaper’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/rmapshaper’
ERROR: dependency ‘rmapshaper’ is not available for package ‘MazamaSpatialUtils’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/MazamaSpatialUtils’
ERROR: dependencies ‘MazamaSpatialUtils’, ‘raster’, ‘sf’ are not available for package ‘PWFSLSmoke’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/PWFSLSmoke’
ERROR: dependency ‘MazamaSpatialUtils’ is not available for package ‘MazamaLocationUtils’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/MazamaLocationUtils’

The downloaded source packages are in
        ‘/tmp/Rtmp8ABJLk/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
✔  checking for file ‘/tmp/Rtmp8ABJLk/remotes3e7e529426f5a/MazamaScience-AirSensor-98985b8/DESCRIPTION’ (358ms)
─  preparing ‘AirSensor’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘AirSensor/docker’
   Removed empty directory ‘AirSensor/documents’
   Removed empty directory ‘AirSensor/pkgdown’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘AirSensor_1.0.9.tar.gz’ (656ms)
   Warning: invalid uid value replaced by that for user 'nobody'
   
ERROR: dependencies ‘MazamaLocationUtils’, ‘MazamaSpatialUtils’, ‘PWFSLSmoke’ are not available for package ‘AirSensor’
* removing ‘/nas/longleaf/home/praful/anaconda3/envs/r_env/lib/R/library/AirSensor’
There were 21 warnings (use warnings() to see them)

**Comment by jonathancallahan** [comment]
The error messages seem self-evident:

```
Configuration failed because libjq was not found. Try installing:

deb: libjq-dev (Debian, Ubuntu).
rpm: jq-devel (Fedora, EPEL)
csw: libjq_dev (Solaris)
brew: jq (OSX)
If is already installed set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

Did you try installing the appropriate jq package for your system based on the guidance above?
