### ISSUE TITLE
Web service error 500

### ISSUE THREAD

**Issue by emaldonado-rti** [MazamaScience/AirSensor#275]
The code I am running was running perfectly a week ago. I tried yesterday (6/1) and this morning(6/2) and I keep running into issues regarding the baseURL with the pas_createNew function. I think its the server just don't know if this is something that is getting fixed or if I need a new baseURL.
> pas5 <- pas_createNew(countryCodes = c("US"))

ERROR [2022-06-02 07:40:24] Web service failed to respond: https://www.purpleair.com/json?all=true
ERROR [2022-06-02 07:40:24] web service error 500 from https://www.purpleair.com/json?all=true: Internal Server Error
Error in pas_downloadParseRawData(baseUrl) : 
  web service error 500 from https://www.purpleair.com/json?all=true: Internal Server Error

**Comment by jonathancallahan** [comment]
For package support questions and answers, please join the MazamaPackageSupport Slack Workspace channel for the AirSensor package:

https://join.slack.com/t/mazamapackagesupport/shared_invite/zt-1a3xlu2f6-W4wtEThRhUPlpX9JuNrXZg

**Comment by jeremymack-LU** [comment]
Sorry, I wasn't able to join the Slack workspace, but I noticed the pas objects have not updated on the server since 5/27.

> pas <- pas_load()
Error: Data file could not be loaded after 30 tries

**Comment by jonathancallahan** [comment]
@jeremymack-LU I just sent an invitation to your LU email that should allow you to join the Slack channel.

The bottom line is that PurpleAir changed their data API and the **AirSensor** package has not yet been updated to handle it. Workarounds are discussed in the #air-sensor Slack channel.

**Comment by jeremymack-LU** [comment]
@jonathancallahan, thanks for update and the invite - appreciate it.

**Comment by Seren-Smith** [comment]
Hello, I'm a researcher and PhD student at George Mason University who is interested in looking at this data over the Fourth of July- may I have an invitation to the Slack?

**Comment by jonathancallahan** [comment]
Hi Seren-Smith. I'll need your email to send you an invite.

**Comment by jonathancallahan** [comment]
Or try this link within the next 7 days: 

https://join.slack.com/t/mazamapackagesupport/shared_invite/zt-1cg1pkrv7-PkQ8AjPQCBsrVJLgu6Os3Q

**Comment by LDV26** [comment]
Hello, I was wondering if I could also get an invite? I am a Ph.D. student at UT, and I am currently working on a community monitoring network; and would like to look over the recent data that has been acquired.

**Comment by jonathancallahan** [comment]
Here is another invite link that will expire on September 1'st:

https://join.slack.com/t/mazamapackagesupport/shared_invite/zt-1dkzyg2v7-KiOuELZgj~JdFOTDOOnKxw
