### ISSUE TITLE
pas data only available until May 27, 2022

### ISSUE THREAD

**Issue by jsawich** [MazamaScience/AirSensor#276]
Dear developers, 

unfortunately, the sensor pas are only available until 2022 05 27. What could be the issue? 

This is the archive that the package tries to access: http://air-sensor-data.mazamascience.com/PurpleAir/v1/pas/2022/

Thank you very much in advance.

**Comment by jonathancallahan** [comment]
This package has not yet been modified to handle the change in the PurpleAir API that occurred on that date. We are currently seeking funding to support the new API. For updates, you can join a Slack channel dedicated to this and other "Mazama Science" packages related to environmental monitoring data:

https://join.slack.com/t/mazamapackagesupport/shared_invite/zt-1g5sb1tjr-CiVCcS7ZGWQiGnVMOeAwVA
